package com.mr.gof.creational.builder.bankreport;

/**
 * Concrete Builder that produces a detailed, audit-ready financial report.
 * This version includes breakdowns, risk metrics, and regulatory data.
 */
public class DetailedReportBuilder implements BankReportBuilder {

    private final BankReport report = new BankReport();

    @Override
    public void buildHeader() {
        report.setHeader("Detailed Report — Full Financial Breakdown");
    }

    @Override
    public void buildBody() {
        report.setBody("""
                Accounts:
                  - Checking: 70,000
                  - Savings: 40,000
                  - Business: 10,000

                Deposits:
                  - Retail: $2.1B
                  - Corporate: $2.1B

                Loans:
                  - Personal: $600M
                  - Mortgage: $900M
                  - Business: $300M

                Risk Metrics:
                  - NPL Ratio: 2.1%
                  - Liquidity Coverage: 118%
                """);
    }

    @Override
    public void buildFooter() {
        report.setFooter("Generated by DetailedReportBuilder — Audit Ready");
    }

    @Override
    public BankReport getReport() {
        return report;
    }
}
