package com.github.biddaisy.gof.creational.builder.bankreport;

/**
 * Concrete Builder that produces a regulatory-compliant report.
 * This version focuses on mandatory disclosures, compliance metrics,
 * and audit trails required by regulators (e.g., Basel III, IFRS9, AML/KYC).
 */
public class RegulatoryReportBuilder implements BankReportBuilder {

    private final BankReport report = new BankReport();

    @Override
    public void buildHeader() {
        report.setHeader("Regulatory Compliance Report — Basel III / IFRS9");
    }

    @Override
    public void buildBody() {
        report.setBody("""
                Mandatory Disclosures:
                  - Capital Adequacy Ratio: 14.2%
                  - Tier 1 Capital Ratio: 11.8%
                  - Liquidity Coverage Ratio (LCR): 122%
                  - Net Stable Funding Ratio (NSFR): 108%

                Risk & Compliance:
                  - AML Flags Reviewed: 3,120
                  - KYC Refresh Completed: 98.7%
                  - Suspicious Activity Reports Filed: 42

                Audit Trail:
                  - Report Generated: System Automated Process
                  - Data Sources: Core Banking, Risk Engine, Compliance DB
                """);
    }

    @Override
    public void buildFooter() {
        report.setFooter("Generated by RegulatoryReportBuilder — For Regulator Submission Only");
    }

    @Override
    public BankReport getReport() {
        return report;
    }
}
