package com.github.biddaisy.gof.creational.builder.bankreport;

/**
 * Concrete Builder that produces a lightweight, high-level summary report.
 * This version is intended for executives or dashboards.
 */
public class SummaryReportBuilder implements BankReportBuilder {

    private final BankReport report = new BankReport();

    @Override
    public void buildHeader() {
        report.setHeader("Summary Report — High‑Level Overview");
    }

    @Override
    public void buildBody() {
        report.setBody("""
                - Total Accounts: 120,000
                - Total Deposits: $4.2B
                - Total Loans: $1.8B
                """);
    }

    @Override
    public void buildFooter() {
        report.setFooter("Generated by SummaryReportBuilder");
    }

    @Override
    public BankReport getReport() {
        return report;
    }
}
